version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command:
      - /bin/bash
      - -c
      - |
        bash bundle update && 
        bundle install && 
        bundle exec jekyll serve --watch --force_polling --verbose 
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll